# Generated by Django 4.0.6 on 2022-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.FileField(upload_to='problem/static/problem/'),
        ),
    ]
